parameters:
- name: projectName
  displayName: Project Type
  type: string
  default: volte
  values:
  - Volte
  - VoWifi
  - 5G
  
- name: productName
  displayName: Product Name
  type: string
  default: CFX
  values:
  - CFX
  - TAS
  - NEF  
  
- name: releaseName
  displayName: Release
  type: string
  default: 20.5
  values:
  - 20.5
  - 20.8
  - 21.0  
  
  
- name: customer
  displayName: Customer name
  type: string
  default: NAM
  
  

- name: designRequired
  type: boolean
  default: false
  
  
- name: deploymentRequired
  type: boolean
  default: false


trigger: none

stages:

- stage: Requirement
  displayName: ${{ parameters.customer }} ${{ parameters.projectName }}
  pool:
    name: default
  jobs:
  - job: requirement
    displayName: Requirement for ${{ parameters.productName }} ${{ parameters.releaseName }}
    steps:
    - script: >             
        rm -rf /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }};        
        mkdir -p /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }};        
        echo "customerName= ${{ parameters.customer }};projectName=${{ parameters.projectName }};productName=${{ parameters.productName }};release=${{ parameters.releaseName }}" > /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}/projectDetails.txt
        
    - task: PythonScript@0
      displayName: create Jira for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}
      continueOnError: true
      enabled: true
      inputs:
        scriptPath: /home/sistudio/agent/jira/createIssue.py
        arguments: 'create'
        pythonInterpreter: /usr/bin/python3
        workingDirectory: /home/sistudio/agent/${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}

- ${{ if eq(parameters.designRequired, true) }}:   
    - stage: Design
      displayName: Design for ${{ parameters.productName }} ${{ parameters.releaseName }}
      pool:
        name: default
      jobs:
      - ${{ if contains(parameters.productName, 'CFX') }}:
          - job: Design4CFX
            displayName: Design for ${{ parameters.productName }} ${{ parameters.releaseName }}
            steps:
            - task: PythonScript@0
              displayName: 'Plato Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              timeoutInMinutes: 100000
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u ppareek -p Marvel@2020'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3
                
      - ${{ if contains(parameters.productName, 'TAS') }}:
          - job: Design4TAS
            displayName: Design  ${{ parameters.productName }} ${{ parameters.releaseName }}
            steps:
            - task: PythonScript@0
              displayName: 'Plato Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u ppareek -p Marvel@2020'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3
                
      - ${{ if contains(parameters.productName, 'NEF') }}:
          - job: Design4NEF
            displayName: Design for ${{ parameters.productName }} ${{ parameters.releaseName }}
            steps:
            - task: PythonScript@0
              displayName: 'Plato Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u ppareek -p Marvel@2020'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3

- ${{ if eq(parameters.deploymentRequired, true) }}:
    - stage: Deployment
      displayName: ${{ parameters.productName }} ${{ parameters.releaseName }} Deployment
      pool:
        name: default
      jobs:
      - job: build
        displayName: 'Depyment is required for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}'
        steps:
        - script: echo deployment started for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}
