parameters:
- name: projectName
  displayName: Project Name
  type: string
  default: volte
  values:
  - volte
  - VoWifi
  - 5Gcore
  
- name: productName
  displayName: Product Name
  type: string
  default: volte
  values:
  - CFX
  - TAS
  - NEF  
  
- name: releaseName
  displayName: release Name
  type: string
  default: volte
  values:
  - 20.5
  - 20.8
  - 21.0  

trigger: none

stages:

- stage: Requirement
  displayName: project Requirement
  jobs:
  - job: requirement
    displayName: Requirement    
    steps:
    - script: echo starting  $(Build.BuildNumber) with ${{ parameters.projectName }}      
   
- stage: Design
  displayName: Design
  jobs:
  - job: Design
    displayName: Design
    steps:
    - task: PythonScript@0
      displayName: 'Plato Login'
      inputs:
        scriptPath: /home/thomas/plato/plato.py
        arguments: 'login -u ppareek -p Marvel@2020'
        pythonInterpreter: /usr/bin/python3
        workingDirectory: /home/thomas/plato/

    - task: PythonScript@0
      displayName: 'Plato Create Project'
      inputs:
        scriptPath: /home/thomas/plato/plato.py
        arguments: 'createProject -f NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
        pythonInterpreter: /usr/bin/python3

    - task: PythonScript@0
      displayName: 'Download XML'
      inputs:
        scriptPath: /home/thomas/plato/plato.py
        arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
        pythonInterpreter: /usr/bin/python3

- stage: Deployment
  displayName: project Deployment
  jobs:
  - job: build
    displayName: 'trigger the deployment for '
    steps:
    - script: echo deployment started for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}
