parameters:
- name: productName
  displayName: Product Name
  type: string
  default: NEF
  values:
  - CFX
  - TAS
  - NEF

- name: releaseName
  displayName: Product Version
  type: string
  default: 20.8
  values:
  - 20.5
  - 20.8
  - 21.0

- name: customer
  displayName: Customer Name
  type: string
  default: 

- name: projectName
  displayName: Project Name
  type: string
  default: 

 
- name: requiredPhase
  displayName: Requirement Phase
  type: boolean
  default: false
  
- name: designRequired
  displayName: Design Phase
  type: boolean
  default: false


- name: onboardingPrep
  displayName: Onboarding Prep
  type: boolean
  default: false

- name: onboardingPreChk
  displayName: CNF Onboarding Pre Checks
  type: boolean
  default: false
  
- name: onboardingReq
  displayName: CNF Onboarding
  type: boolean
  default: false

- name: onboardingPostChk
  displayName: CNF Onboarding Post Checks
  type: boolean
  default: false
  
- name: nonfunctional
  displayName: Non Functional Test Suite
  type: boolean
  default: false
  
trigger: none

stages:
- ${{ if eq(parameters.requiredPhase, true) }}:
    - stage: Requirement
      displayName: ${{ parameters.customer }} ${{ parameters.projectName }}
      pool:
        name: default
      jobs:
      - job: requirement
        displayName: 'Requirement Phase started for ${{ parameters.customer }} ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
        steps:
        - script: >
            rm -rf /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }};
            mkdir -p /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }};
            echo "customerName= ${{ parameters.customer }};projectName=${{ parameters.projectName }};productName=${{ parameters.productName }};release=${{ parameters.releaseName }}" > /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}/projectDetails.txt

        - task: PythonScript@0
          displayName: JIRA create Task for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/jira/createIssue.py
            arguments: ''
            pythonInterpreter: /usr/bin/python3
            
        - task: PythonScript@0
          displayName: 'GIT: fork Blueprint Artefacts for ${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/git/createBranch.py
            arguments: nwzXQaN34DyzD9NHWQ8U 29761 ${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}
            pythonInterpreter: /usr/bin/python3
          
        

- ${{ if eq(parameters.designRequired, true) }}:
    - stage: Design
      displayName: Design for ${{ parameters.productName }} ${{ parameters.releaseName }}
      pool:
        name: default
      jobs:
      - ${{ if contains(parameters.productName, 'CFX') }}:
          - job: Design4CFX
            displayName: 'Design Phase started for ${{ parameters.productName }} ${{ parameters.releaseName }}'
            steps:
            - task: PythonScript@0
              displayName: 'Jira : Add  Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/jira/addComment.py
                arguments: 'Design_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
                pythonInterpreter: /usr/bin/python3
            - task: PythonScript@0
              displayName: 'Plato: Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u suparash -p Fashion2020!'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato: Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f /home/sistudio/agent/plato/NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Plato: Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3

      - ${{ if contains(parameters.productName, 'TAS') }}:
          - job: Design4TAS
            displayName: 'Plato: Design Phase for ${{ parameters.productName }} ${{ parameters.releaseName }}'
            steps:
            - task: PythonScript@0
              displayName: 'Jira: Add Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/jira/addComment.py
                arguments: 'Design_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
                pythonInterpreter: /usr/bin/python3
            - task: PythonScript@0
              displayName: 'Plato: Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u suparash -p Fashion2020!'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato: Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f /home/sistudio/agent/plato/NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Plato: Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3

      - ${{ if contains(parameters.productName, 'NEF') }}:
          - job: Design4NEF
            displayName: Design Phase for ${{ parameters.productName }} ${{ parameters.releaseName }}
            steps:
            - task: PythonScript@0
              displayName: 'Jira: Add Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/jira/addComment.py
                arguments: 'Design_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
                pythonInterpreter: /usr/bin/python3
            - task: PythonScript@0
              displayName: 'Plato: Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u suparash -p Fashion2020!'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato: Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f /home/sistudio/agent/plato/NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Plato: Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3
                
- ${{ if eq(parameters.onboardingPreChk, true) }}:
    - stage: OnboardingPreChk
      displayName: ${{ parameters.productName }} ${{ parameters.releaseName }} Onboarding Precheck
      pool:
        name: default
      jobs:
      - job: build
        displayName: 'Onboarding Precheck Phase for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}'
        steps:        
        - task: PythonScript@0
          displayName: 'Onboarding Precheck started for ${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/deployment/check.py 
            arguments: 'precheck'
            pythonInterpreter: /usr/bin/python3


- ${{ if eq(parameters.onboardingReq, true) }}:
    - stage: Onboarding
      displayName: ${{ parameters.productName }} ${{ parameters.releaseName }} Onboarding
      pool:
        name: default
      jobs:
      - job: build
        displayName: 'Onboarding Phase for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}'
        steps:
        - task: PythonScript@0
          displayName: 'Jira: Add Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/jira/addComment.py
            arguments: 'Onboarding_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
            pythonInterpreter: /usr/bin/python3
        - task: PythonScript@0
          displayName: 'Onboarding started for ${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/deployment/deployment.py
            arguments: ''
            pythonInterpreter: /usr/bin/python3
            
- ${{ if eq(parameters.onboardingPostChk, true) }}:
    - stage: OnboardingPostChk
      displayName: ${{ parameters.productName }} ${{ parameters.releaseName }} Onboarding Postcheck
      pool:
        name: default
      jobs:
      - job: build
        displayName: 'Onboarding PostCheck Phase for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}'
        steps:        
        - task: PythonScript@0
          displayName: 'Onboarding Postcheck started for ${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/deployment/check.py 
            arguments: 'postcheck'
            pythonInterpreter: /usr/bin/python3
            
- ${{ if eq(parameters.nonfunctional, true) }}:
    - stage: NonFunctional
      displayName: ${{ parameters.productName }} ${{ parameters.releaseName }} Onboarding NonFunctional
      pool:
        name: default
      jobs:
      - job: build
        displayName: 'Non Functional Test case Phase for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}'
        steps:        
        - task: PythonScript@0
          displayName: 'Non Functional Test cases  started for ${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/deployment/check.py 
            arguments: 'nonfunctional'
            pythonInterpreter: /usr/bin/python3