parameters:
- name: productName
  displayName: Product Name
  type: string
  default: NEF
  values:
  - CFX
  - TAS
  - NEF

- name: releaseName
  displayName: Product Version
  type: string
  default: 20.8
  values:
  - 20.5
  - 20.8
  - 21.0

- name: customer
  displayName: Customer Name
  type: string
  default: VodafoneIndia

- name: projectName
  displayName: Project Name
  type: string
  default: NefPoc

- name: token4GIT
  displayName: Token for Git
  type: string
  default: token4GIT


- name: token4JIRA
  displayName: Token for JIRA
  type: string
  default: token4Jira
  
  
  
- name: designRequired
  displayName: Design Phase
  type: boolean
  default: false


- name: deploymentRequired
  displayName: Deployment Phase
  type: boolean
  default: false
  
- name: requiredPhase
  displayName: Requirement Phase
  type: boolean
  default: false


trigger: none

stages:
- ${{ if eq(parameters.requiredPhase, true) }}:
    - stage: Requirement
      displayName: ${{ parameters.customer }} ${{ parameters.projectName }}
      pool:
        name: default
      jobs:
      - job: requirement
        displayName: 'Requirement for ${{ parameters.customer }} ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
        steps:
        - script: >
            rm -rf /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }};
            mkdir -p /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }};
            echo "customerName= ${{ parameters.customer }};projectName=${{ parameters.projectName }};productName=${{ parameters.productName }};release=${{ parameters.releaseName }}" > /home/sistudio/agent/${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}/projectDetails.txt

        - task: PythonScript@0
          displayName: create Jira for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/jira/createIssue.py
            arguments: ''
            pythonInterpreter: /usr/bin/python3
            
        - task: PythonScript@0
          displayName: 'create branch in GIT for   ${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/git/createBranch.py
            arguments: $${ parameters.token4GIT }} 29761 ${{ parameters.customer }}_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}
            pythonInterpreter: /usr/bin/python3

- ${{ if eq(parameters.designRequired, true) }}:
    - stage: Design
      displayName: Design for ${{ parameters.productName }} ${{ parameters.releaseName }}
      pool:
        name: default
      jobs:
      - ${{ if contains(parameters.productName, 'CFX') }}:
          - job: Design4CFX
            displayName: 'Design for ${{ parameters.productName }} ${{ parameters.releaseName }}'
            steps:
            - task: PythonScript@0
              displayName: 'Add  Jira Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/jira/addComment.py
                arguments: 'Design_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
                pythonInterpreter: /usr/bin/python3
            - task: PythonScript@0
              displayName: 'Plato Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u suparash -p Fashion2020!'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f /home/sistudio/agent/plato/NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3

      - ${{ if contains(parameters.productName, 'TAS') }}:
          - job: Design4TAS
            displayName: 'Design  ${{ parameters.productName }} ${{ parameters.releaseName }}'
            steps:
            - task: PythonScript@0
              displayName: 'Add  Jira Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/jira/addComment.py
                arguments: 'Design_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
                pythonInterpreter: /usr/bin/python3
            - task: PythonScript@0
              displayName: 'Plato Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u suparash -p Fashion2020!'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f /home/sistudio/agent/plato/NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3

      - ${{ if contains(parameters.productName, 'NEF') }}:
          - job: Design4NEF
            displayName: Design for ${{ parameters.productName }} ${{ parameters.releaseName }}
            steps:
            - task: PythonScript@0
              displayName: 'Add  Jira Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/jira/addComment.py
                arguments: 'Design_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
                pythonInterpreter: /usr/bin/python3
            - task: PythonScript@0
              displayName: 'Plato Login for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'login -u suparash -p Fashion2020!'
                pythonInterpreter: /usr/bin/python3
                workingDirectory: /home/sistudio/agent/plato/

            - task: PythonScript@0
              displayName: 'Plato Create Project for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'createProject -f /home/sistudio/agent/plato/NEF_NEF205_devops.xlsx -n myNEFProject -c NOK'
                pythonInterpreter: /usr/bin/python3

            - task: PythonScript@0
              displayName: 'Download XML for ${{ parameters.productName }} ${{ parameters.releaseName }}'
              continueOnError: true
              enabled: true
              inputs:
                scriptPath: /home/sistudio/agent/plato/plato.py
                arguments: 'downloadConfiguration  -n myNEFProject -t nef.xml'
                pythonInterpreter: /usr/bin/python3

- ${{ if eq(parameters.deploymentRequired, true) }}:
    - stage: Deployment
      displayName: ${{ parameters.productName }} ${{ parameters.releaseName }} Deployment
      pool:
        name: default
      jobs:
      - job: build
        displayName: 'Depyment is required for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}'
        steps:
        - task: PythonScript@0
          displayName: 'Add  Jira Comment for  ${{ parameters.projectName }} ${{ parameters.productName }} ${{ parameters.releaseName }}'
          continueOnError: true
          enabled: true
          inputs:
            scriptPath: /home/sistudio/agent/jira/addComment.py
            arguments: 'Deployment_started_for_${{ parameters.projectName }}_${{ parameters.productName }}_${{ parameters.releaseName }}'
            pythonInterpreter: /usr/bin/python3
        - script: echo deployment started for  ${{ parameters.productName }}  and release ${{parameters.releaseName}}
